[package]
name = 'AptosArena'
version = '1.0.0'

[addresses]
aptos_arena = '0xc09622c20bdd49b2b83b7e05c264a62cfedeb45eaf5c629d0f0174917d801aef'

[dependencies.AptosArcadeCore]
git = 'https://github.com/aptos-arcade/aptos-arcade-core-contracts'
rev = 'master'
