[package]
name = 'AptosArena'
version = '1.0.0'

[addresses]
aptos_arena = '0xd71b4784f28cd0b0f6d629a0042b88e9e2faad13abc8e85389c48f9445745983'

[dependencies.AptosArcadeCore]
git = 'https://github.com/aptos-arcade/aptos-arcade-core-contracts'
rev = 'master'
